services:
  - type: web
    name: community-backend
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: |
      cd backend
      gunicorn core.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DB_NAME
        value: mydatabase
      - key: DB_USER
        value: myuser
      - key: DB_PASSWORD
        value: mypassword
      - key: DB_HOST
        value: mysqldb
      - key: DB_PORT
        value: 3306

  - type: mysql
    name: mysqldb
    plan: standard
    disk:
      sizeGB: 10
    env:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
