services:
  - type: web
    name: community-backend
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: |
      cd backend
      gunicorn core.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DB_NAME
        value: railway
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        value: mysql-production-397e.up.railway.app
      - key: DB_PORT
        value: 3306
